### ISSUE TITLE
Back Propagation in hard_roi_mining

### ISSUE THREAD

**Issue by PamixSun** [unsky/ohem-end2end#2]
In this implementation of OHEM-end2end, all back propagation options are set to be false in the hard_roi_mining layer. This is strange, since this would stop that gradient of loss_cls and loss_bbox from optimizing  the rpn-related parameters and hence significantly slow the convergence speed of rpn_loss_cls as well as rpn_loss_bbox. At least in my own case, I observe this phenomenon. 

Anyone who encounter the same problems may discuss with me at this issue.

**Comment by unsky** [comment]
@PamixSun the readonly network in ohem do not backward. i think you should read the paper, and understand why

**Comment by PamixSun** [comment]
@unsky 

My concern is in the definition of hard_roi_mining layer:

layer {
  name: "hard_roi_mining"
  type: "Python"
  bottom: "cls_prob_readonly"
  bottom: "bbox_pred_readonly"
  bottom: "rois"
  bottom: "labels"
  bottom: "bbox_targets"
  bottom: "bbox_inside_weights"
  bottom: "bbox_outside_weights"
  top: "rois_hard"
  top: "labels_hard"
  top: "bbox_targets_hard"
  top: "bbox_inside_weights_hard"
  top: "bbox_outside_weights_hard"
  propagate_down: false
  propagate_down: false
  propagate_down: false
  propagate_down: false
  propagate_down: false
  propagate_down: false
  propagate_down: false
  python_param {
    module: "roi_data_layer.layer_ohem"
    layer: "OHEMDataLayer"
    param_str: "'num_classes': 3"
  }
}

I understand that we should not back propagate through "cls_prob_readonly" and "bbox_pred_readonly" , which corresponding to the readonly Network, but why we also need to hinder all the other paths.

**Comment by unsky** [comment]
@PamixSun   e.. readonly-network is share params  with rcnn, so,we don't back  back propagate through "cls_prob_readonly" and "bbox_pred_readonly" .

the method of share params in caffe is like:

layer {
  name: "fc7"
  type: "InnerProduct"
  bottom: "fc6"
  top: "fc7"
  param {
    name: "fc7_w"
    lr_mult: 1
  }
  param {
    name: "fc7_b"
    lr_mult: 2
  }
  inner_product_param {
    num_output: 4096
  }
}


and


layer {
  name: "fc7_readonly"
  type: "InnerProduct"
  bottom: "fc6_readonly"
  top: "fc7_readonly"
  propagate_down: false
  param {
    name: "fc7_w"
  }
  param {
    name: "fc7_b"
  }
  inner_product_param {
    num_output: 4096
  }
}

the name :
  param {
    name: "fc7_w"
  }
  param {
    name: "fc7_b"
  }



**so  we have update the params of rcnn == we have update the params of readonly-network**
